name: OIDC Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  REPO: ${{ vars.ECR_REPOSITORY }}
  TAG: ${{ github.ref_name }}

jobs:
  test-oidc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: check Who am I?
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Export REGISTRY
        run: echo "REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

      - name: Build and push image to ECR
        run: |
          docker build -t "$REGISTRY/$REPO:$TAG" .
          docker push "$REGISTRY/$REPO:$TAG"

      - name: Pull image for test
        run: |
          docker pull "$REGISTRY/$REPO:$TAG"
          docker run --rm "$REGISTRY/$REPO:$TAG"

      - name: create a test file
        run: |
          echo "Hello ! i will be on s3 by $(date -u)" > s3-test.txt
          ls -la

      - name: Upload to S3
        env:
          BUCKET: ${{ vars.S3_BUCKET }}
        run: |
          aws s3 cp s3-test.txt "s3://$BUCKET/oidc-test/s3-test-${{ github.run_id }}.txt"

      - name: Download from S3
        env:
          BUCKET: ${{ vars.S3_BUCKET }}
        run: |
          aws s3 cp "s3://$BUCKET/oidc-test/s3-test-${{ github.run_id }}.txt" downloaded.txt
          cat downloaded.txt
